# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DataTuple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('fieldType', models.CharField(max_length=30)),
                ('clientType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ClientType')),
            ],
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=b'')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='producttype',
            name='requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Requirements'),
        ),
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductType'),
        ),
        migrations.AddField(
            model_name='datatuple',
            name='productType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductType'),
        ),
        migrations.AddField(
            model_name='datatuple',
            name='requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Requirements'),
        ),
        migrations.AddField(
            model_name='clienttype',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Industry'),
        ),
        migrations.AddField(
            model_name='client',
            name='clientType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ClientType'),
        ),
    ]
