# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170909_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDataTuple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('fieldType', models.CharField(max_length=30)),
                ('clientType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ClientType')),
            ],
        ),
        migrations.RemoveField(
            model_name='datatuple',
            name='clientType',
        ),
        migrations.RemoveField(
            model_name='datatuple',
            name='productType',
        ),
        migrations.RemoveField(
            model_name='datatuple',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='DataTuple',
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
        migrations.AddField(
            model_name='requireddatatuple',
            name='productType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductType'),
        ),
        migrations.AddField(
            model_name='requireddatatuple',
            name='reqType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required', to='product.ProductType'),
        ),
    ]
