# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170909_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(editable=False, max_length=100)),
                ('key', models.CharField(editable=False, max_length=300)),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='batchkey',
            name='product',
        ),
        migrations.RemoveField(
            model_name='node',
            name='parent',
        ),
        migrations.DeleteModel(
            name='BatchKey',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
