# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170909_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchentry',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='product.Product'),
        ),
    ]
